version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum update -y
      - yum install -y java-17-openjdk-devel wget
      - echo Installing Gradle 9.0.0...
      - wget https://services.gradle.org/distributions/gradle-9.0.0-bin.zip
      - unzip gradle-9.0.0-bin.zip -d /opt/gradle
      - export PATH=$PATH:/opt/gradle/gradle-9.0.0/bin
      - gradle --version
      - echo Dependencies installed

  pre_build:
    commands:
      - echo Entering pre-build phase...
      - gradle --version
      - echo Pre-build phase complete

  build:
    commands:
      - echo Building the application...
      - gradle build
      - echo Build phase complete

  post_build:
    commands:
      - echo Entering post-build phase...
      - mv build/libs/my-app.jar my-app.jar
      - echo Post-build phase complete

artifacts:
  files:
    - my-app.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/**/*'
