version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum install -y java-17-openjdk-devel wget unzip docker
      - echo Installing Gradle 8.12.1...
      - wget https://services.gradle.org/distributions/gradle-8.12.1-bin.zip
      - unzip gradle-8.12.1-bin.zip -d /opt/gradle
      - export PATH=$PATH:/opt/gradle/gradle-8.12.1/bin
      - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      - export PATH=$JAVA_HOME/bin:$PATH
      - gradle --version
      - echo Dependencies installed

  pre_build:
    commands:
      - echo Entering pre-build phase...
      - gradle --version
      - echo Pre-build phase complete

  build:
    commands:
      - echo Building the application...
      - gradle clean build
      - echo Running unit tests...
      - gradle test
      - echo Build phase complete
      - echo Building Docker image...
      - docker build -t salary_calculator .
      - echo Docker image built successfully.

  post_build:
    commands:
      - echo Entering post-build phase...
      - echo Pushing Docker image...
      - docker tag salary_calculator:latest <mrkotula>/salary_calculator:latest
      - docker push <mrkotula>/salary_calculator:latest
      - echo Post-build phase complete

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/**/*'
