version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum update -y
      - yum install -y java-17-openjdk-devel wget unzip
      - echo Installing Gradle 7.5...
      - wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
      - unzip gradle-7.5-bin.zip -d /opt/gradle
      - export PATH=/opt/gradle/gradle-7.5/bin:$PATH
      - gradle --version
      - echo Dependencies installed

  pre_build:
    commands:
      - echo Entering pre-build phase...
      - gradle --version
      - echo Pre-build phase complete

  build:
    commands:
      - echo Building the application...
      - gradle clean build --stacktrace --info
      - echo Build phase complete

  post_build:
    commands:
      - echo Entering post-build phase...
      - mv build/libs/SalaryCalculator-0.0.1-SNAPSHOT.jar SalaryCalculator-0.0.1-SNAPSHOT.jar
      - echo Post-build phase complete

artifacts:
  files:
    - SalaryCalculator-0.0.1-SNAPSHOT.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/**/*'