version: 0.2

install:
  runtime-versions:
    java: corretto17

pre_build:
  commands:
    - echo Entering test phase...
    - gradle --version

build:
  commands:
    - echo Running tests...
    - gradle test
    - echo Test phase complete

reports:
  junit:
    files:
      - 'build/test-results/test/*.xml'
    file-format: "JUNITXML"

artifacts:
  files:
    - build/reports/**/*
  discard-paths: no
