spring:
  application:
    name: SalaryCalculator

  datasource:
    url: ${POSTG_DB_URL}
    username: ${POSTG_DB_USERNAME}
    password: ${POSTG_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
